### ISSUE TITLE
A border around image, or something to distinguish images from text would improve readability

### ISSUE THREAD

**Issue by abhn** [hhariri/hhariri.github.io#9]
Hello Hadi,

Nice blog. Love the content. I think if you can create margins around images or not have images with white backgrounds full width or even borders/shadows around images, it would greatly improve readability. 

![Screenshot 2020-01-22 at 11 59 48](https://user-images.githubusercontent.com/6270406/72888864-bc86aa80-3d0e-11ea-90ab-77c6cbb7dc63.png)

Currently it is hard to see where an image ends and your commentary starts. 

Cheers!
Abhishek

**Comment by hhariri** [comment]
Thank you. I'll look into it.
